name: build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-22-04:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build (with UBSan)
      run: make ubsan EXTRA_CFLAGS=" -Werror"
    - name: Run tests
      run: make test

  build-ubuntu-24-04:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build (with UBSan)
      run: make ubsan EXTRA_CFLAGS=" -Werror"
    - name: Run tests
      run: make test

  build-debian-bullseye:
    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (apt-get)
      run: apt-get update && apt-get -y install build-essential
    - name: Simple build (no tests / UBSan)
      run: make EXTRA_CFLAGS=" -Werror"
